name: 🐧 Linux Builds
on: [push, pull_request]


jobs:
  linux-editor:
    runs-on: "ubuntu-20.04"
    name: Editor

    steps:
      - uses: actions/checkout@v2

      # Azure repositories are not reliable, we need to prevent azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo add-apt-repository ppa:oibaf/graphics-drivers -y
          sudo apt update
          sudo apt install xorg -y
          sudo apt-get install build-essential pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm -y
          sudo apt install wget git unzip tar xvfb -y
          sudo apt upgrade -y

      # Setup scons, print python version and scons version info, so if anything is broken it won't run the build.
      - name: Configuring Python packages
        run: |
          wget https://archive.hugo.pro/builds/godot/master/editor/godot-linux-nightly-x86_64.zip
          unzip godot-linux-nightly-x86_64.zip

      - name: Run
        run: |
          LIBGL_ALWAYS_SOFTWARE=true xvfb-run ./godot -q
