name: CI

on:
  push:
    branches: [ master, 3.2, 3.1, 3.0, qqq ]
  pull_request:
    branches: [ master, 3.2, 3.1, 3.0, qqq ]

jobs:

  linux-mono:
    runs-on: windows-2019
    name: Windows

    steps:
    - uses: actions/checkout@v2


    - name: Compilation
      run: |
        scons -j6 platform=windows
        

