name: CI

on:
  push:
    branches: [ master, 3.2, 3.1, 3.0, qqq ]
  pull_request:
    branches: [ master, 3.2, 3.1, 3.0, qqq ]

jobs:


  javascript:
    runs-on: ubuntu-latest
    name: Javascript

    steps:
    - uses: actions/checkout@v2

    - name: Dependency installation
      run: |
        sudo apt update
        sudo apt upgrade -y
        
        sudo apt install -y build-essential scons pkg-config libx11-dev libxcursor-dev libxinerama-dev libgl1-mesa-dev libglu-dev libasound2-dev libpulse-dev libudev-dev libxi-dev libxrandr-dev yasm
        sudo apt install -y git
        
    - name: Change Python version
      run: |
        sudo rm /usr/bin/python
        sudo ln -s /usr/bin/python3 /usr/bin/python

    - name: Emsdk
        git clone --depth 1 "https://github.com/emscripten-core/emsdk.git";
        ./emsdk/emsdk install latest;
        ./emsdk/emsdk activate latest;

    - name: Compilation
      run: |
        scons platform=javascript tools=no target=release -j6 


  ios-arm64:
    runs-on: macos-latest
    name: ios ARM64

    steps:
    - uses: actions/checkout@v2

    - name: Dependency installation
      run: |
        brew install scons yasm

    - name: Compilation
      run: |
        scons p=iphone arch=x86_64 target=debug

  ios-arm:
    runs-on: macos-latest
    name: ios ARM

    steps:
    - uses: actions/checkout@v2

    - name: Dependency installation
      run: |
        brew install scons yasm

    - name: Compilation
      run: |
        scons p=iphone tools=no target=release arch=arm
