name: CI

on:
  push:
    branches: [ master, 3.2, 3.1, 3.0, qqq ]
  pull_request:
    branches: [ master, 3.2, 3.1, 3.0, qqq ]

jobs:

 


  ios-arm64:
    runs-on: macos-latest
    name: ios ARM64

    steps:
    - uses: actions/checkout@v2

    - name: Dependency installation
      run: |
        brew install scons yasm

    - name: Compilation
      run: |
        scons p=iphone arch=x86_64 target=debug

  ios-arm:
    runs-on: macos-latest
    name: ios ARM

    steps:
    - uses: actions/checkout@v2

    - name: Dependency installation
      run: |
        brew install scons yasm

    - name: Compilation
      run: |
        scons p=iphone tools=no target=release arch=arm
